export enum Screen {
  AUTHNAVIGATOR = 'AuthNavigator',
  GUESTNAVIGATOR = 'GuestNavigator',
  HOMESTACK = 'HomeStack',
  HOMEDRAWER = 'HomeDrawer',
  SETTINGSTACK = 'SettingStack',
  EXPLORESTACK = 'ExploreStack',
  LOGIN = 'Login',
  REGISTER = 'Register',
  HOME = 'Home',
  SETTINGSCREEN = 'SettingScreen',
  SETTING = 'Setting',
  MENU = 'Menu',
  EXPLORE = 'Explore',
  AUCTIONWINNERS = 'AuctionWinners',
  PRODUCT_DETAIL = 'ProductDetail',
}
